/**
 * System Prompt Merge Engine
 * 
 * 手動入力されたシステムプロンプトと自動生成された能力・制約情報を
 * LLMを使って自然に統合する
 */

import { z } from 'zod';

// マージリクエストのスキーマ
export const SystemPromptMergeRequestSchema = z.object({
  manualPrompt: z.string().describe('User-provided manual system prompt'),
  autoGeneratedInfo: z.object({
    llmLimitations: z.object({
      contextWindowLimit: z.number(),
      maxResponseTokens: z.number(),
      processingConstraints: z.array(z.string())
    }),
    capabilities: z.object({
      expertise: z.array(z.string()),
      tools: z.array(z.string()),
      responsibilities: z.array(z.string())
    }),
    restrictions: z.object({
      forbiddenOperations: z.array(z.string()),
      safetyRequirements: z.array(z.string()),
      ethicalConstraints: z.array(z.string())
    })
  }),
  mergeStrategy: z.enum(['complement', 'enhance', 'validate']).default('complement'),
  conflictResolution: z.enum(['manual_priority', 'auto_priority', 'llm_judgment']).default('llm_judgment')
});

export type SystemPromptMergeRequest = z.infer<typeof SystemPromptMergeRequestSchema>;

// マージ結果のスキーマ
export const SystemPromptMergeResultSchema = z.object({
  success: z.boolean(),
  mergedPrompt: z.string().optional(),
  conflicts: z.array(z.object({
    type: z.enum(['contradiction', 'ambiguity', 'incompatibility']),
    description: z.string(),
    manualPart: z.string(),
    autoPart: z.string(),
    suggestedResolution: z.string()
  })),
  rejectionReason: z.string().optional(),
  warnings: z.array(z.string()).default([]),
  mergeMetadata: z.object({
    strategy: z.string(),
    llmModel: z.string(),
    timestamp: z.string(),
    tokensUsed: z.number().optional()
  })
});

export type SystemPromptMergeResult = z.infer<typeof SystemPromptMergeResultSchema>;

export class SystemPromptMergeEngine {
  private llmManager: any; // LLMManagerの参照

  constructor(llmManager: any) {
    this.llmManager = llmManager;
  }

  /**
   * メイン処理：システムプロンプトのマージ
   */
  async mergeSystemPrompt(request: SystemPromptMergeRequest): Promise<SystemPromptMergeResult> {
    try {
      // 1. 入力データの検証
      const validatedRequest = SystemPromptMergeRequestSchema.parse(request);
      
      // 2. 矛盾検出
      const conflicts = await this.detectConflicts(validatedRequest);
      
      // 3. 重大な矛盾がある場合は拒否
      const criticalConflicts = conflicts.filter(c => c.type === 'incompatibility');
      if (criticalConflicts.length > 0) {
        return this.createRejectionResult(criticalConflicts, validatedRequest);
      }
      
      // 4. LLMによるマージ実行
      const mergedPrompt = await this.performLLMMerge(validatedRequest, conflicts);
      
      // 5. 結果の構築
      return {
        success: true,
        mergedPrompt,
        conflicts,
        warnings: this.generateWarnings(conflicts),
        mergeMetadata: {
          strategy: validatedRequest.mergeStrategy,
          llmModel: 'gpt-4', // TODO: 実際のモデル名を取得
          timestamp: new Date().toISOString(),
          tokensUsed: undefined // TODO: トークン使用量を計算
        }
      };
      
    } catch (error) {
      return {
        success: false,
        conflicts: [],
        rejectionReason: `Merge processing failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
        warnings: [],
        mergeMetadata: {
          strategy: request.mergeStrategy || 'complement',
          llmModel: 'unknown',
          timestamp: new Date().toISOString()
        }
      };
    }
  }

  /**
   * 矛盾検出：手動プロンプトと自動生成情報の矛盾を特定
   */
  private async detectConflicts(request: SystemPromptMergeRequest): Promise<Array<{
    type: 'contradiction' | 'ambiguity' | 'incompatibility';
    description: string;
    manualPart: string;
    autoPart: string;
    suggestedResolution: string;
  }>> {
    const conflicts = [];
    
    // LLMによる矛盾検出
    const conflictDetectionPrompt = `
Analyze the following manual system prompt and auto-generated capability information for conflicts:

Manual Prompt:
"${request.manualPrompt}"

Auto-Generated Information:
- Expertise: ${request.autoGeneratedInfo.capabilities.expertise.join(', ')}
- Tools: ${request.autoGeneratedInfo.capabilities.tools.join(', ')}
- Limitations: Context window ${request.autoGeneratedInfo.llmLimitations.contextWindowLimit} tokens, max response ${request.autoGeneratedInfo.llmLimitations.maxResponseTokens} tokens
- Restrictions: ${request.autoGeneratedInfo.restrictions.forbiddenOperations.join(', ')}

Identify any conflicts between manual instructions and auto-generated constraints. Return as JSON array with structure:
[{
  "type": "contradiction|ambiguity|incompatibility",
  "description": "description of conflict",
  "manualPart": "conflicting part from manual prompt",
  "autoPart": "conflicting auto-generated constraint",
  "suggestedResolution": "how to resolve this conflict"
}]
`;

    try {
      const response = await this.llmManager.generateMessage([
        { role: 'user', content: conflictDetectionPrompt }
      ], {
        maxTokens: 1000,
        temperature: 0.3
      });

      const detectedConflicts = JSON.parse(response.content);
      conflicts.push(...detectedConflicts);
    } catch (error) {
      console.warn('Conflict detection failed, proceeding without conflict analysis:', error);
    }

    return conflicts;
  }

  /**
   * LLMによるマージ実行
   */
  private async performLLMMerge(
    request: SystemPromptMergeRequest, 
    conflicts: any[]
  ): Promise<string> {
    const mergePrompt = this.buildMergePrompt(request, conflicts);
    
    const response = await this.llmManager.generateMessage([
      { role: 'user', content: mergePrompt }
    ], {
      maxTokens: 2000,
      temperature: 0.5
    });

    return response.content.trim();
  }

  /**
   * マージ用プロンプトの構築
   */
  private buildMergePrompt(request: SystemPromptMergeRequest, conflicts: any[]): string {
    const { manualPrompt, autoGeneratedInfo, mergeStrategy } = request;
    
    return `
You are a system prompt integration specialist. Your task is to merge a user's manual system prompt with auto-generated technical capability information.

## Manual System Prompt (User Intent):
"${manualPrompt}"

## Auto-Generated Technical Information:
### Capabilities:
- Expertise: ${autoGeneratedInfo.capabilities.expertise.join(', ')}
- Available Tools: ${autoGeneratedInfo.capabilities.tools.join(', ')}
- Responsibilities: ${autoGeneratedInfo.capabilities.responsibilities.join(', ')}

### Technical Limitations:
- Context Window: ${autoGeneratedInfo.llmLimitations.contextWindowLimit} tokens
- Max Response: ${autoGeneratedInfo.llmLimitations.maxResponseTokens} tokens
- Processing Constraints: ${autoGeneratedInfo.llmLimitations.processingConstraints.join(', ')}

### Restrictions:
- Forbidden Operations: ${autoGeneratedInfo.restrictions.forbiddenOperations.join(', ')}
- Safety Requirements: ${autoGeneratedInfo.restrictions.safetyRequirements.join(', ')}
- Ethical Constraints: ${autoGeneratedInfo.restrictions.ethicalConstraints.join(', ')}

${conflicts.length > 0 ? `
## Detected Conflicts:
${conflicts.map(c => `- ${c.description}: ${c.suggestedResolution}`).join('\n')}
` : ''}

## Merge Strategy: ${mergeStrategy}
- complement: Add technical info without changing manual intent
- enhance: Strengthen manual prompt with technical details  
- validate: Ensure compatibility and flag issues

## Instructions:
1. Preserve the core intent and personality from the manual prompt
2. Seamlessly integrate technical limitations and capabilities
3. Resolve any conflicts using the suggested resolutions
4. Create a natural, coherent system prompt that works in practice
5. Use English for technical constraints and Japanese for personality aspects if appropriate

Return only the merged system prompt, no additional commentary.
`;
  }

  /**
   * 拒否結果の作成
   */
  private createRejectionResult(
    criticalConflicts: any[], 
    request: SystemPromptMergeRequest
  ): SystemPromptMergeResult {
    const rejectionReason = `Cannot merge due to incompatible requirements:\n${
      criticalConflicts.map(c => `- ${c.description}`).join('\n')
    }\n\nSuggested fixes:\n${
      criticalConflicts.map(c => `- ${c.suggestedResolution}`).join('\n')
    }`;

    return {
      success: false,
      conflicts: criticalConflicts,
      rejectionReason,
      warnings: [],
      mergeMetadata: {
        strategy: request.mergeStrategy,
        llmModel: 'conflict-detector',
        timestamp: new Date().toISOString()
      }
    };
  }

  /**
   * 警告メッセージの生成
   */
  private generateWarnings(conflicts: any[]): string[] {
    const warnings = [];
    
    const contradictions = conflicts.filter(c => c.type === 'contradiction');
    if (contradictions.length > 0) {
      warnings.push(`${contradictions.length} contradictions were resolved automatically`);
    }
    
    const ambiguities = conflicts.filter(c => c.type === 'ambiguity');
    if (ambiguities.length > 0) {
      warnings.push(`${ambiguities.length} ambiguous instructions were clarified`);
    }
    
    return warnings;
  }
}
